logicalclocks/karamel-chef

- cluster.yml.3.hopsworks
Add kagent::dev to the run list
NOTICE: https://github.com/karamelchef/kagent-chef/pull/11 should also be merged!
> HOPSWORKS-81

- cluster.yml.1.hopsworks
Disable cuda installation by default
https://hopshadoop.atlassian.net/browse/HOPSWORKS-105
> HOPSWORKS-105

- kill.sh
- run.sh
Change subnet so that it does not overlap with existing private networks
Change subnet only for multi VM setup
Remove VBox virtual interface when killing multi VM deployment
https://hopshadoop.atlassian.net/browse/HOPSWORKS-117
> HOPSWORKS-117

- Vagrantfile.ubuntu.1
- Vagrantfile.ubuntu.3
Pin to specific image of bento/ubuntu-16.04 because of libc and JNI issues
https://hopshadoop.atlassian.net/browse/HOPSWORKS-132
> HOPSWORKS-132

- README.md
- dela_env.sh
- hs_env.sh
Documentation:
README.md 
comments in the hs_env.sh and dela_env.sh
> HOPSWORKS-94

- cluster-defns/3.hops_tls_enabled.yml
- vagrantfiles/Vagrantfile.ubuntu.3
Add cluster definition for Hops TLS enabled and forward Hadoop debug ports
> [hops_ssl_enabled]  Add cluster definition for Hops TLS enabled

- cluster-defns/3.hopsworks_secure.yml
[HOPS-187]  Enable CRL validation and set development CRL fetcher class
[HOPS-187]  Fetch CRL more frequently for dev
https://hopshadoop.atlassian.net/browse/HOPS-187
> [HOPS-187]  Enable Hops CRL validation

- cluster-defns/1.secure.yml
- cluster-defns/3.hopsworks_secure.yml
https://hopshadoop.atlassian.net/browse/HOPSWORKS-519
> [HOPSWORKS-519]  Change Hops RPC TLS attributes

- cluster-defns/3.hopsworks_secure.yml
Override RM certificate actor class with the development version
> [HOPS-291]  Override RM certificate actor class

- cluster-defns/3.hopsworks.yml
- cluster-defns/3.hopsworks_secure.yml
Add tensorflow recipe to all machines in a 3 VM setup
> [add_tf_all_groups]  Append Tf recipe

- cluster-defns/1.secure.yml
- cluster-defns/3.hopsworks_secure.yml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-645
> [HOPSWORKS-645]  Enable DataNode Data Transfer encryption for secure cluster definitions

- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-582
> [HOPSWORKS-582]  Use the FQDN when changing the hosts file

- dela/templates/1.dela_template.yml
- dela/templates/1.hopssite_template.yml
- dela/vm_image_scripts/csr-ca.py
Add filebeat to dela recipe.
Update dela deploy scripts.
> [HOPSWORKS-695] Updates related to PR 695

- templates/default/rspec_env.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-753
> [HOPSWORKS-753]  Set MySQL socket location for tests

- cluster-defns/1.hops.yml
- cluster-defns/3.hops.yml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-808
> [HOPSWORKS-808] fix hops cluster definition in karamel-chef

- cluster-defns/1.hopsworks.yml
- cluster-defns/3.hopsworks.yml
- cluster-defns/3.hopsworks_secure.yml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-916
> [HOPSWORKS-916]  Add filebeat-kagent recipe to run list

- cluster-defns/1.hopsworks-kerberos.yml
- cluster-defns/1.hopsworks-ldap.yml
> [HOPSWORKS-944] krb cluster def

- recipes/test.rb
- Skip regular tests when running it-tests
> HOPSWORKS-998 append

- recipes/it_tests.rb
- add integration test for serving API in hops-util-py
> [HOPSWORKS-751] add support for SkLearn model serving

- attributes/default.rb
- cluster-defns/aws.1.hops.yml
- cluster-defns/aws.1.hopsworks.yml
- cluster-defns/gce.1.hops.yml
- cluster-defns/gce.1.hopsworks.yml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1307
> [HOPSWORKS-1037][Karamel] Fixes to release Karamel 0.6

- cluster-defns/3.hopsworks.yml
- cluster-defns/3.hopsworks_secure.yml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1027
https://github.com/logicalclocks/hops-testing/pull/512
> [HOPSWORKS-1027] Add support for multiple elasticsearch nodes (HA)

- recipes/build.rb
add new module/profile for testing only endpoints. build the artifacts with this module for testing on jenkings
> testingProfile

- attributes/default.rb
- recipes/test.rb
- templates/default/rspec_env.erb
Add elastic user and pass to be used in http requests.
Add epipe host.
> [HOPSWORKS-1372] elastic and epipe attributes in env file

- hopsworks-installer.sh
Hopsworks Installer improvements
> [HOPSWORKS-1617] Add

- recipes/test.rb
- templates/default/rbenv_check.erb
- templates/default/rbenv_install.erb
the rbenv_install.sh and rbenv_check.sh are split so we have time to setup rbenv correctly(PATH and others) before checking, otherwise the script will return 1 instead of 0 and the bash block might fail.
> ubuntu rbenv-ruby install fix

- cloud/azure/_create.sh
- cloud/azure/config.sh
- cloud/gcp/config.sh
- cloud/gcp/config.sh.centos
- cloud/gcp/config.sh.ubuntu
- cloud/util/install.sh
- cluster-defns/hopsworks-installer.yml
- hopsworks-installer.sh
Separate cluster definition branch from hopsworks-chef branch. 
Azure fix: dont prompt for DNS hostname when running in non-interactive mode.
> Installer improvements

- cloud/azure/_create.sh
- cloud/gcp/_create.sh
- cloud/gcp/_list_private.sh
- cloud/gcp/_list_public.sh
- cloud/gcp/benchmark.sh
- cloud/gcp/config.sh
- cloud/gcp/list.sh
- hopsworks-installer.sh
branch/github url now separate env variables in hopsworks-installer.sh
> Gcp - filter by zone

- cloud/util/install.sh
- hopsworks-installer.sh
Also added to hopsworks-installer
> Add nexus username/password to gcp/azure installations

- cloud/util/install.sh
- hopsworks-installer.sh
Input from command-line now, as well as env variables.
> Ask user for nexus password in gcp/azure installations

- cloud/util/install.sh
It can have bad side-effects of subsequent installations trying to install k8s.
> dont rewrite branchname in hopsworks-installer.sh for k8s

- cloud/gcp/benchmark.sh
- cloud/util/install.sh
> fix benchmark script issue

- attributes/default.rb
- recipes/test.rb
To be merged with https://github.com/tkakantousis/hops-testing-ee/commit/8b8a2aac608c4635035fb64fe4acb260f2c47f45
> [HOPSWORKS-1743] Report Hopsworks UT

- cloud/gcp/config.sh
- cloud/gcp/list.sh
- cluster-defns/hopsworks-installer.yml
- hopsworks-installer.sh
Ask user if they need a http_proxy to access the internet when installing with karamel
> http-installer http_proxy support

- cluster-defns/1.hops.yml
- cluster-defns/3.hops.yml
- cluster-defns/aws.1.hops.yml
- cluster-defns/gce.1.hops.yml
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1807
> [HOPSWORKS-1807] fix hops cluster definition to work without docker

- cloud/README.md
- cloud/hopsworks-cloud-installer.sh
- hopsworks-installer.sh
Add a new type of dry-run for the cloud installer that creates the VMs but doesn't run Karamel.
> [HOPSWORKS-1976]  Add 

- cloud/README.md
- cloud/hopsworks-cloud-installer.sh
- cluster-defns/hopsworks-head.yml
- hopsworks-installer.sh
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1976
> [HOPSWORKS-1976] Add

- cloud/hopsworks-cloud-installer.sh
- cloud/install-enterprise-1-vm-k8s-gcp.sh
>  [HOPSWORKS-1976] Add 

- cloud/helper-scripts/install-enterprise-1-vm-k8s-gcp.sh
- cloud/hopsworks-cloud-installer.sh
- cluster-defns/hopsworks-head.yml
- hopsworks-installer.sh
Some bash changes to work on a mac
> Cloud installer fixes for Mac

- cloud/helper-scripts/custom-localhost.sh
- cloud/helper-scripts/install-enterprise-1-vm-k8s-gcp.sh
- cloud/hopsworks-cloud-installer.sh
- cluster-defns/hopsworks-head.yml
- hopsworks-installer.sh
hops/yarn/gpus attribute removed.
Fixes for multi-node on GCP.
> Changes to cluster definition

- cluster-defns/hopsworks-head.yml
> Installer multinode fixes

- hopsworks-installer.sh
Disabling it doesn't work. might as well just install it by default if you want k8s.
> enable kfserving

- cloud/hopsworks-cloud-installer.sh
- hopsworks-installer.sh
Installer needs to be set to install version 2.2, not master
> update version to 2.2 for installer

- cloud/hopsworks-cloud-installer.sh
Ensured that changes that made $i variables local by calling
them $az_i and $gc_i was made throughout.
Ensured that setting boot size worked
Removed clear screen for improved debuggability
Wait 1 minute after creating VMs to ensure that SSH service has
started on the VMs before proceeding.
> Fixes of RonDB cloud installer scripts

- run.sh
>  [HOPSWORKS-3030]  append 

- cluster-defns/hopsworks-head.yml
enable python kernel correctly.
> fix for installer

- cluster-defns/1.hopsworks-ee.yml
- cluster-defns/1.hopsworks.yml
- vagrantfiles/Vagrantfile.centos.1
- vagrantfiles/Vagrantfile.ubuntu.1
tested on dev vm together with https://github.com/logicalclocks/flyingduck-chef/pull/14
> [FSTORE-837] add flyginduck to single node configs

- cloud/examples/gcp-gpu.sh
- cloud/examples/gcp-k8s-nvme.sh
- cloud/hopsworks-cloud-installer.sh
- hopsworks-installer.sh
> GPU updates

- vagrantfiles/Vagrantfile.centos.1
- vagrantfiles/Vagrantfile.ubuntu-mysql.1
- vagrantfiles/Vagrantfile.ubuntu.1
Add port forward for additional services: 
- Istio
- Kafka
- Opensearch
- RonDB Rest Server
> Add port forward for additional services in single VM vagrantfiles
